spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: admin
    drive-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dbl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true